### ISSUE TITLE
issue running server code 

### ISSUE THREAD

**Issue by cyamac1993** [IBM/fabric-contract-attribute-based-access-control#18]
Hi,
First of all, I'm very thankful for sharing your code.
After running server.js code I get this error :

Error connecting to Fabric network. TypeError: FileSystemWallet is not a constructor
Error in connecting to Fabric network.  TypeError: gateway.getClient is not a function
    at Object.utils.events (/Users/biekzadehsiamak/Desktop/iBM_vsCode/fabric-contract-attribute-based-access-control/application/server/utils.js:133:28)
    at main (/Users/biekzadehsiamak/Desktop/iBM_vsCode/fabric-contract-attribute-based-access-control/application/server/server.js:37:21)

**Comment by ElangSBP** [comment]
Hi, I already test the code and it's working properly as long you follow the instruction carefully, and don't try to upgrade the dependencies and convert the the JavaScript files to ES6 Module because it will broke the program.
